dia = input('Qual é o dia do seu nascimento?')
mes = input('Qual é o mês que você nasceu?')
ano = input('Qual é o ano do seu nascimento?')
idade = 2025 - int(ano)
print('Você nasceu no dia', dia, 'de', mes, 'de', ano, 'e tem', idade, 'anos de idade' '. Correto?')